build:
  test:
    image: maven:3-jdk-8-onbuild
    commands:
      - mvn surefire-report:report
      - cp target/site/tools.html .framgia-ci-reports/tools.html
    when:
      event: [push, tag, pull_request]
  publish:
    image: tannv85/tomcat8
    commands:
      - framgia-ci run -d -p 8080:8080 -p 8009:8009 -v target:/opt/tomcat/webapps
    when:
      branch: master
      event: push

cache:
  mount:
    - .git
    - /drone/.m2

debug: true