cache:
  mount:
    - /drone/.m2
build:
  main:
    image: maven:3-jdk-8-onbuild
      commands:
         - mvn package -Dmaven.repo.local=/drone/.m2
         - mvn test -Dmaven.repo.local=/drone/.m2
         - mvn surefire-report:report-only
         - echo "Build has been completed."

      when:
       event: [push, tag]
debug: true