build:
  test-unit:
    image: tannv85/maven3.9-jdk8
    volumes:
      - target:/opt/tomcat/webapps
    commands:
      - mvn clean site
      - mkdir .framgia-ci-reports/unit-test/
      - cp target/site/* .framgia-ci-reports/unit-test/
      - framgia-ci run
    when:
      event: [push, tag, pull_request]

  test-unit:
      image: tannv85/maven3.9-jdk8
      volumes:
        - target:/opt/tomcat/webapps
      commands:
        - mvn clean install
        - mvn sonar:sonar
        - mkdir .framgia-ci-reports/coverage/
        - cp target/site/* .framgia-ci-reports/coverage/
        - framgia-ci run
      when:
        event: [push, tag, pull_request]

compose:
  database:
    image: mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_pw
      MYSQL_ROOT_PASSWORD: root

cache:
  mount:
    - .git
    - /drone/.m2

debug: true