cache:
  mount:
    - /drone/.m2
build:
  main:
    image: maven:3-jdk-8-onbuild
      commands:
         - sleep 15
         - mysql -u root -h 127.0.0.1:3306
         - mvn package -Dmaven.repo.local=/drone/.m2
         - mvn test -Dmaven.repo.local=/drone/.m2
         - mvn surefire-report:report-only
         - echo "Build has been completed."

debug: true