cache:
  mount:
    - /drone/.m2
build:
  main:
    image: maven:3-jdk-8-onbuild
    commands:
      - mvn clean install -DskipTests -Dmaven.repo.local=/drone/.m2
      - echo "Build has been completed."
      - mvn surefire-report:report
      - cp target/site/tools.html .framgia-ci-reports/tools.html
    when:
      event: [push, tag]

services:
  mysql:
    image: mysql:5.6.27
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER =tannv
      - MYSQL_PASSWORD=tannv
debug: true