cache:
  mount:
    - /drone/.m2
build:
  main:
    image: maven:3-jdk-8-onbuild
    commands:
      - mvn surefire-report:report
      - echo "Create Reports has been completed."
      - cp target/site/tools.html .framgia-ci-reports/tools.html
    when:
      event: [push, tag]
report:
  # regex syntax to extract values
  source:
    - path/to/file.txt
    - path/to/folder/ #
debug: true