cache:
  mount:
    - /drone/.m2
build:
  main:
    image: maven:3-jdk-8-onbuild
    commands:
      - mvn clean install -Dmaven.repo.local=/drone/.m2
      - echo "Build has been completed."
      - mvn surefire-report:report-only
      - echo "Create Reports has been completed."
      - cp target/site/tools.html .framgia-ci-reports/tools.html
    when:
      event: [push, tag]
debug: true